# Generated by Django 2.0.5 on 2018-08-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopaypal',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Cotizacion'),
        ),
    ]
