# Generated by Django 2.0.5 on 2018-08-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='despachado',
            field=models.BooleanField(default=False),
        ),
    ]
