"""
Django settings for etc project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'opx5yc+m@+miro-nn5p6ecb2--hp2p^^5c+uj0hydqt7a3hr1_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'apps.usuarios',
    'apps.pagos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'etc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'etc',
        'USER':'andres',
        'PASSWORD':'1234',
        'HOST':'127.0.0.1',
        'PORT':'3306', 

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

}
# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

AUTH_USER_MODEL = "usuarios.User" 
#AUTH_USER_MODEL = "usuarios.User" 

STATIC_URL = '/static/'
#MEDIA_URL = '/media/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
FILE_ROOT=os.path.join(BASE_DIR, 'files')
MEDIA_URL = '/media/'
FILE_URL = '/files/'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'home'

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'objetosaprendizajeslibres@gmail.com'
EMAIL_HOST_PASSWORD = 'PassWord12345'


CRISPY_TEMPLATE_PACK = 'bootstrap4'


SITE_URL = 'http://127.0.0.1:8000'

#Credenciales de PayPal
PAYPAL_MODE= "sandbox"
#PAYPAL_CLIENT_ID  = "AdLvQZ2abXeFBLOubgyuiUsFejSVUTny5qG-zb3BG_SZNjsaf4b884G07YhnvdoJHgujSd1iRRtAy9-m"
#PAYPAL_CLIENT_SECRET = "EDbe1J6ZKV8sCtCJBJzmA-GPF4t4V9i6foFALlQga__3m3EZNYX_yq4SrOadok1aIHgC4kANqORsMRKf"

PAYPAL_CLIENT_ID  = "ATLxSTKroZGswqMDC2EjTSGAjJQXxpE8bEpM1b6Ul57HEuoL4RTy7q51wEohHjwgUqOwv3KR29KS9bLZ"
PAYPAL_CLIENT_SECRET = "EIvVRAcBTqsuuIcDgSngyDTQrQLWb3Yaawgr62LzoxOn1KZdwfhMw__0QrJNu-pda3hoScPRCVhFH_mM"



EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'objetosaprendizajeslibres@gmail.com'
EMAIL_HOST_PASSWORD = 'PassWord12345'